name: Deploy to AWS Lightsail

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Lightsail via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.UG_LIGHTSAIL_AWS }}
          script: |
            # Clone the repository into the actionTest directory
            git clone https://github.com/fadhilabdulla-puremagic/testPipeline.git /var/www/html/actionTest

            # Change to the actionTest directory
            cd /var/www/html/actionTest

            # Install dependencies
            npm install

            # Build the React app
            npm run build

            # Optionally, remove the previous build files if necessary
            # sudo rm -rf /var/www/html/actionTest/*

            # Copy the build files to the desired location if needed
            # cp -r build/* /var/www/html/actionTest/
