name: Deploy to AWS Lightsail

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Lightsail
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }} # Your server's IP address
          username: ubuntu
          key: ${{ secrets.UG_LIGHTSAIL_AWS }} # Your server's SSH private key
          script: |
            cd /var/www/html/actionTest/
            git pull
            npm install
            npm run build
