name: Deploy to AWS Lightsail

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Lightsail via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.UG_LIGHTSAIL_AWS }}
          script: |
            # Change to the actionTest directo
            cd /var/www/html/actionTest

            # Clone the repository into the actionTest directory
            git pull origin main

            # Install dependencies
            npm install

            # Build the React app
            npm run build
